name: Daily Stock Data Fetcher

on:
  schedule:
    - cron: '0 17 * * 1-5'  # Mon–Fri at 6PM WAT (WAT is UTC+1)
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pandas==2.2.2 selenium==4.21.0 webdriver-manager==4.0.2

    - name: Run stock data fetch script
      run: python database_setup/fetch_stock_data.py
