name: Run Signal Generation with TA-Lib

on:
  schedule:
    - cron: '0 18 * * 5'  # Every Friday at 6 PM WAT
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alphalensio/ta-lib:latest  # Includes TA-Lib C lib + Python bindings preinstalled

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upgrade pip and install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run signal generation script
      run: python database_setup/generate_signals.py
