name: Run TA-Lib Signal Generator with Custom Dockerfile

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 5'  # Every Friday at 6 PM WAT

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image with TA-Lib
      run: |
        docker build -f database_setup/Dockerfile.ta-lib -t talib-env .

    - name: Run signal generation inside TA-Lib container
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app talib-env \
          bash -c "pip install -r requirements.txt && python database_setup/generate_signals.py"
