name: Build and Cache TA-Lib

on:
  schedule:
    - cron: '0 18 * * 5'  # Runs every Friday at 6 PM (WAT)
  workflow_dispatch:  # Manually trigger the workflow if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2  # Ensure using the latest v2 version
      with:
        python-version: '3.8'

    - name: Cache TA-Lib
      id: cache-talib
      uses: actions/cache@v3  # Use the latest v3 for the cache action
      with:
        path: /usr/local/lib/python3.8/dist-packages/ta-lib  # Adjust path for caching TA-Lib
        key: ${{ runner.os }}-talib-${{ hashFiles('**/ta-lib-0.4.0-src.tar.gz') }}  # Cache key

    - name: Build TA-Lib from Source
      if: steps.cache-talib.outputs.cache-hit != 'true'  # Only build if not cached
      run: |
        echo "Building TA-Lib from source"
        # Download TA-Lib source
        curl -L https://github.com/markeisha/ta-lib/releases/download/v0.4.19/ta-lib-0.4.19-src.tar.gz -o ta-lib-0.4.19-src.tar.gz
        tar -xvzf ta-lib-0.4.19-src.tar.gz
        cd ta-lib
        # Build TA-Lib
        ./configure --prefix=/usr
        make
        sudo make install
        echo "TA-Lib installed successfully"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run signal generation script
      run: python database_setup/generate_signals.py  # Run the script after all dependencies are installed
