name: Weekly Signal Generation

on:
  schedule:
    # This will run every Friday at 6 PM WAT (West Africa Time)
    - cron: '0 18 * * 5'  # Adjust the timing if needed (UTC+1 is 18:00 WAT)
  workflow_dispatch:  # Allows you to manually trigger the workflow if needed

jobs:
  generate-signals:
    runs-on: ubuntu-latest  # Run on a GitHub-hosted Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can change to any Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have pandas, talib, etc., in requirements.txt

    - name: Run signal generation script
      run: python generate_signals.py  # Runs the Python script to generate signals
