name: Build and Cache TA-Lib

on:
  schedule:
    - cron: '0 18 * * 5'  # Runs every Friday at 6 PM (WAT)
  workflow_dispatch:  # Manually trigger the workflow if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Cache TA-Lib source
      id: cache-talib
      uses: actions/cache@v4
      with:
        path: ~/ta-lib
        key: ${{ runner.os }}-talib-0.4.0

    - name: Build and Install TA-Lib
      if: steps.cache-talib.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential automake autoconf libtool wget
        mkdir -p ~/ta-lib
        cd ~/ta-lib
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xvzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib
        ./configure --prefix=/usr/local
        make
        sudo make install
        sudo ldconfig

    - name: Install Python bindings for TA-Lib
      env:
        LD_LIBRARY_PATH: /usr/local/lib
        CFLAGS: -I/usr/local/include
        LDFLAGS: -L/usr/local/lib
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install ta-lib

    - name: Install project dependencies
      run: |
        pip install -r requirements.txt

    - name: Run signal generation script
      run: python database_setup/generate_signals.py
