# .github/workflows/run-signals.yml

name: Run Signal Generator with pandas-ta

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 5'  # Every Friday at 6 PM WAT

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -f database_setup/Dockerfile.ta-pandas -t signal-env .

    - name: Run signal generation inside container
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app signal-env
